"""create table ratings

Revision ID: 5d77a511a265
Revises: 
Create Date: 2020-06-29 13:41:31.363456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d77a511a265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('queue', sa.String(length=20), nullable=True),
    sa.Column('callerid', sa.String(length=20), nullable=True),
    sa.Column('opinion', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_callerid'), 'ratings', ['callerid'], unique=False)
    op.create_index(op.f('ix_ratings_operator'), 'ratings', ['operator'], unique=False)
    op.create_index(op.f('ix_ratings_queue'), 'ratings', ['queue'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_queue'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_operator'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_callerid'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
