"""create table

Revision ID: e2657c0a5d1c
Revises: 
Create Date: 2020-07-14 12:06:13.383223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2657c0a5d1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('queue', sa.String(length=20), nullable=True),
    sa.Column('callerid', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_callerid'), 'ratings', ['callerid'], unique=False)
    op.create_index(op.f('ix_ratings_created_at'), 'ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ratings_operator'), 'ratings', ['operator'], unique=False)
    op.create_index(op.f('ix_ratings_queue'), 'ratings', ['queue'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_queue'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_operator'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_created_at'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_callerid'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
